name: GitHub Test
on:
  workflow_dispatch:
    inputs:
      c_one: 
        type: choice
        description: "First Variable"
        options:
          - "Do"
          - "Dont do"
        default: "Do"
  push:
    branches:
      - main
      - release/*
env:
  var_one: "Dont do"

jobs:
  test-input:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Check the trigger
        run: echo "${{ github.event_name }}"
      - name: set action
        run: |
          echo "Set up environment"
          if [[ ${{ github.event_name }} == "workflow_dispatch"  ]]
          then
            echo "Action=${{ github.event.inputs.c_one }}" >> $GITHUB_ENV
          elif [[ ${{ github.event_name }} == "push" ]]
          then
            echo "Action=${{ env.var_one }}" >> $GITHUB_ENV
          fi 

      - name: Check Action value
        run: |
          echo "${{ env.Action }}"
          echo "${{ github.run_number }}"

  
