name: GitHub Test
permissions: write-all

on:
  workflow_dispatch:
    inputs:
      c_one: 
        type: choice
        description: "First Variable"
        options:
          - "Do"
          - "Dont do"
        default: "Do"
  push:
    branches:
      - main
      - release/*
env:
  var_one: "Dont do"

jobs:
  test-input:
    runs-on: "ubuntu-22.04"
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check the trigger
        run: echo "${{ github.event_name }}"
      - name: set action
        run: |
          echo "Set up environment"
          if [[ ${{ github.event_name }} == "workflow_dispatch"  ]]
          then
            echo "Action=${{ github.event.inputs.c_one }}" >> $GITHUB_ENV
          elif [[ ${{ github.event_name }} == "push" ]]
          then
            echo "Action=${{ env.var_one }}" >> $GITHUB_ENV
          fi 

      - name: Generate Semantic Versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: semver
        run: |
          git fetch --tags
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:%s | grep -E '^(BREAKING|feat|fix|perf|revert|docs|style|refactor|test|chore)(([a-zA-Z0-9-]+))?:' | cut -d ":" -f 1 | awk 'BEGIN {major=0; minor=0; patch=0} {if ($1 == "feat") minor++; else if ($1 == "fix") patch++; else if ($1 == "BREAKING") major++} END {print major "." minor "." patch}' | awk -F"." '{print "v"$1"."$2"."$3}' | version.txt
 
          echo "tag_name=$(cat version.txt)" >> $GITHUB_ENV
      - name: Create Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(cat version.txt)
          git tag $tag
          git push origin $tag
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: Release ${{ steps.semver.outputs.version }}
          body: |
            Release ${{ steps.semver.outputs.version }}
            Changes:
          draft: false
          prerelease: false    

      - name: Check Action value
        run: |
          echo "${{ env.Action }}"
          echo "${{ github.run_number }}"

  
